use recipes;
INSERT INTO categories (name) VALUES
('Appetizers'),
('Breakfast'),
('Brunch'),
('Lunch'),
('Dinner'),
('Dessert'),
('Snacks'),
('Side Dishes'),
('Soups'),
('Salads'),
('Sauces'),
('Dressings'),
('Breads'),
('Pastas'),
('Pizzas'),
('Casseroles'),
('Stews'),
('Grilling'),
('Baking'),
('Roasting'),
('Frying'),
('Steaming'),
('Poaching'),
('Sautéing'),
('Stir-Frying'),
('Raw'),
('Vegan'),
('Vegetarian'),
('Gluten-Free'),
('Dairy-Free'),
('Paleo'),
('Keto'),
('Low-Carb'),
('Mediterranean'),
('Asian'),
('Italian'),
('Mexican'),
('Indian'),
('French'),
('American'),
('African'),
('Middle Eastern'),
('Seafood'),
('Poultry'),
('Beef'),
('Pork'),
('Lamb'),
('Vegetables'),
('Fruits'),
('Grains'),
('Legumes'),
('Nuts'),
('Seeds'),
('Eggs'),
('Cheese'),
('Chocolate'),
('Vanilla'),
('Spicy'),
('Sweet'),
('Savory'),
('Comfort Food'),
('Holiday'),
('Quick & Easy'),
('Kid-Friendly'),
('Budget-Friendly'),
('Healthy'),
('Low-Fat'),
('High-Protein'),
('One-Pot'),
('Slow Cooker'),
('Instant Pot'),
('Air Fryer'),
('Drinks'),
('Cocktails'),
('Smoothies'),
('Juices'),
('Canning'),
('Preserving'),
('Fermenting'),
('Pickling'),
('Jams & Jellies'),
('Condiments'),
('Marinades'),
('Rubs'),
('Dips'),
('Spreads'),
('Toppings'),
('Cakes'),
('Cookies'),
('Pies'),
('Brownies'),
('Bars'),
('Muffins'),
('Scones'),
('Puddings'),
('Custards'),
('Ice Cream'),
('Sorbet'),
('Frozen Yogurt'),
('Granola'),
('Oatmeal'),
('Pancakes'),
('Waffles'),
('Crepes'),
('Frittatas'),
('Quiches'),
('Tacos'),
('Burritos'),
('Enchiladas'),
('Fajitas'),
('Quesadillas'),
('Nachos'),
('Salsas'),
('Guacamole'),
('Chili'),
('Curries'),
('Stir-Fries'),
('Souvlaki'),
('Kebabs'),
('Tagines'),
('Paella'),
('Risotto'),
('Sushi'),
('Ramen'),
('Pho'),
('Dim Sum'),
('Tapas'),
('Mezze'),
('Antipasto'),
('Charcuterie'),
('Fondue'),
('Raclette'),
('Baguettes'),
('Ciabatta'),
('Sourdough'),
('Biscuits'),
('Cornbread'),
('Rolls'),
('Muffuletta'),
('Po Boys'),
('Cuban Sandwiches'),
('Reubens'),
('Philly Cheesesteaks'),
('Monte Cristos'),
('Club Sandwiches'),
('BLTs'),
('Grilled Cheese'),
('Tuna Melts'),
('French Dips'),
('Meatball Subs'),
('Italian Beef'),
('Pulled Pork'),
('Sloppy Joes'),
('Hot Dogs'),
('Hamburgers'),
('Cheeseburgers'),
('Veggie Burgers'),
('Black Bean Burgers'),
('Turkey Burgers'),
('Salmon Burgers'),
('Chicken Sandwiches'),
('Fish Sandwiches'),
('Shrimp Po Boys'),
('Lobster Rolls'),
('Crab Cakes'),
('Oysters'),
('Clams'),
('Mussels'),
('Scallops'),
('Squid'),
('Octopus'),
('Tuna'),
('Salmon'),
('Cod'),
('Halibut'),
('Swordfish'),
('Trout'),
('Catfish'),
('Tilapia'),
('Snapper'),
('Grouper'),
('Mahi-Mahi'),
('Sea Bass'),
('Sardines'),
('Anchovies'),
('Herring'),
('Mackerel'),
('Eel'),
('Caviar'),
('Foie Gras'),
('Truffles'),
('Saffron'),
('Wasabi'),
('Ginger'),
('Garlic'),
('Onions'),
('Chilies'),
('Herbs'),
('Spices'),
('Vinegar'),
('Oil'),
('Salt'),
('Pepper'),
('Sugar'),
('Honey'),
('Maple Syrup'),
('Molasses'),
('Corn Syrup'),
('Agave Nectar'),
('Stevia'),
('Erythritol'),
('Monk Fruit'),
('Xylitol'),
('Aspartame'),
('Saccharin'),
('Sucralose'),
('Neotame'),
('Acesulfame Potassium'),
('Advantame'),
('Cyclamate'),
('Dulcin'),
('Gluten'),
('Casein'),
('Lactose'),
('Soy'),
('Peanuts'),
('Tree Nuts'),
('Shellfish'),
('Fish'),
('Sesame'),
('Mustard'),
('Celery'),
('Lupin'),
('Molluscs'),
('Sulphites'),
('Alcohol'),
('Caffeine'),
('Nicotine'),
('Drugs'),
('Poisons'),
('Toxins'),
('Allergens'),
('Additives'),
('Preservatives'),
('Artificial Colors'),
('Artificial Flavors'),
('Artificial Sweeteners'),
('GMOs'),
('Organic'),
('Natural'),
('Sustainable'),
('Ethical'),
('Fair Trade'),
('Local'),
('Seasonal'),
('Heirloom'),
('Artisanal'),
('Homemade'),
('Handcrafted'),
('Small Batch'),
('Microbrewed'),
('Craft Beer'),
('Wine'),
('Spirits'),
('Liqueurs'),
('Cordials'),
('Bitters'),
('Syrups'),
('Mixers'),
('Garnishes'),
('Ice'),
('Water'),
('Soda'),
('Tea'),
('Coffee'),
('Milk'),
('Cream'),
('Yogurt'),
('Buttermilk'),
('Sour Cream'),
('Cottage Cheese'),
('Ricotta Cheese'),
('Mascarpone Cheese'),
('Cream Cheese'),
('Brie Cheese'),
('Camembert Cheese'),
('Gouda Cheese'),
('Cheddar Cheese'),
('Swiss Cheese'),
('Mozzarella Cheese'),
('Parmesan Cheese'),
('Romano Cheese'),
('Asiago Cheese'),
('Provolone Cheese'),
('Monterey Jack Cheese'),
('Pepper Jack Cheese'),
('Blue Cheese'),
('Gorgonzola Cheese'),
('Feta Cheese'),
('Halloumi Cheese'),
('Paneer Cheese'),
('Queso Fresco Cheese'),
('Oaxaca Cheese'),
('Manchego Cheese'),
('Pecorino Cheese'),
('Fontina Cheese'),
('Taleggio Cheese'),
('Limburger Cheese'),
('Munster Cheese'),
('Brick Cheese'),
('Colby Cheese'),
('Edam Cheese'),
('Emmental Cheese'),
('Gruyere Cheese'),
('Jarlsberg Cheese'),
('Havarti Cheese'),
('Leerdammer Cheese'),
('Maasdam Cheese'),
('Mimolette Cheese'),
('Port Salut Cheese'),
('Reblochon Cheese'),
('Saint-Nectaire Cheese'),
('Tomme de Savoie Cheese'),
('Vacherin Cheese'),
('Boursin Cheese'),
('Fromage Blanc Cheese'),
('Neufchâtel Cheese'),
('Pimento Cheese'),
('String Cheese'),
('Tofu'),
('Tempeh'),
('Seitan'),
('Jackfruit'),
('Mushrooms'),
('Seaweed'),
('Sprouts'),
('Microgreens'),
('Edible Flowers'),
('Space Food'),
('Future Food'),
('Fusion Cuisine'),
('Molecular Gastronomy'),
('Deconstructed Dishes'),
('Reimagined Classics'),
('Global Flavors'),
('Street Food'),
('Food Trucks'),
('Pop-Up Restaurants'),
('Farm-to-Table'),
('Nose-to-Tail'),
('Zero Waste'),
('Upcycled Food'),
('Aquaponics'),
('Hydroponics'),
('Permaculture'),
('Biodynamic Farming'),
('Community Gardens'),
('Urban Farming'),
('Guerrilla Gardening'),
('Seed Banks'),
('Food Sovereignty'),
('Food Justice'),
('Food Security'),
('Food Deserts'),
('Food Waste'),
('Food Miles'),
('Carbon Footprint');